"""add_api_keys_table

Revision ID: 682ada03d87e
Revises: 7a7921b57d3a
Create Date: 2025-09-23 01:05:18.818512+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "682ada03d87e"
down_revision: str | None = "7a7921b57d3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable name for the API key",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of the API key's purpose",
        ),
        sa.Column(
            "key_hash",
            sa.String(length=255),
            nullable=False,
            comment="Hashed version of the API key",
        ),
        sa.Column(
            "key_prefix",
            sa.String(length=8),
            nullable=False,
            comment="First 8 characters for identification",
        ),
        sa.Column(
            "permissions",
            sa.JSON(),
            nullable=False,
            comment="List of permissions this key has",
        ),
        sa.Column(
            "scopes",
            sa.JSON(),
            nullable=True,
            comment="Additional scopes for fine-grained access",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this key expires",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last time this key was used",
        ),
        sa.Column(
            "usage_count",
            sa.String(length=20),
            nullable=True,
            comment="Number of times this key has been used",
        ),
        sa.Column(
            "created_by",
            sa.String(length=255),
            nullable=True,
            comment="User ID from Supabase auth",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True,
            comment="Whether this key is active",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_keys")
    # ### end Alembic commands ###
