# Database Migrations

This directory contains database migrations managed by Alembic.

## Directory Structure

- `versions/`: Contains individual migration scripts
- `env.py`: Alembic environment configuration
- `script.py.mako`: Template for new migration scripts

## Running Migrations

### Local Development

1. Create a new migration:
```bash
alembic revision --autogenerate -m "description of changes"
```

2. Apply migrations:
```bash
alembic upgrade head
```

3. Rollback migrations:
```bash
alembic downgrade -1  # Roll back one migration
alembic downgrade base  # Roll back all migrations
```

### CI/CD Pipeline

In the CI/CD pipeline, migrations are applied automatically:
```bash
alembic upgrade head
```

## Best Practices

1. Always review autogenerated migrations before committing
2. Test migrations both up and down
3. Include meaningful descriptions in migration names
4. Keep migrations atomic - one conceptual change per migration
5. Add comments in migration scripts to explain complex changes
